using System.Text.Json;
using System.Text.Json.Serialization;
using ObserveAi;

namespace ObserveAi.Tests;

/// <summary>
/// Guards Derived.Derive() against drifting from eval/derived.py's derive(). The
/// vectors in tests/vectors/derived.json were generated by running the Python
/// implementation against eval/logs.jsonl, one row per producer (see each case's
/// "producer" field), so this test is only meaningful as long as that file stays a
/// faithful capture of the Python output.
/// </summary>
public class DerivedTests
{
    public sealed class DerivedVector
    {
        [JsonPropertyName("name")]
        public string Name { get; init; } = "";

        [JsonPropertyName("producer")]
        public string? Producer { get; init; }

        [JsonPropertyName("state")]
        public JsonElement State { get; init; }

        [JsonPropertyName("expected_facts")]
        public List<string> ExpectedFacts { get; init; } = [];

        public override string ToString() => Name;
    }

    public static IEnumerable<object[]> Vectors() => LoadVectors().Select(vector => new object[] { vector });

    private static List<DerivedVector> LoadVectors()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "vectors", "derived.json");
        var json = File.ReadAllText(path);
        return JsonSerializer.Deserialize<List<DerivedVector>>(json) ?? [];
    }

    [Theory]
    [MemberData(nameof(Vectors))]
    public void AgreesWithPythonDerive(DerivedVector vector)
    {
        var facts = Derived.Derive(vector.State);

        Assert.Equal(vector.ExpectedFacts, facts);
    }

    [Fact]
    public void VectorFileCoversAllFourProducers()
    {
        var producers = LoadVectors().Select(vector => vector.Producer).ToHashSet(StringComparer.Ordinal);

        // Containment rather than equality: the vector covers the whole fixture,
        // so most rows produce nothing and carry the "none" producer. Those rows
        // are the guard against a producer firing where it should not.
        foreach (var producer in new[] { "acquire_release", "current_versus_baseline", "durations", "repetition" })
        {
            Assert.Contains(producer, producers);
        }
    }

    [Fact]
    public void WithDerivedAddsFactsArrayWhenEvidenceIsPresent()
    {
        var vector = LoadVectors().First(v => v.Producer == "acquire_release");

        var enriched = Derived.WithDerived(vector.State);

        Assert.True(enriched.TryGetProperty("derived_facts", out var facts));
        Assert.Equal(vector.ExpectedFacts, facts.EnumerateArray().Select(f => f.GetString()));
        // The original fields survive alongside derived_facts.
        Assert.True(enriched.TryGetProperty("evidence", out _));
    }

    [Fact]
    public void WithDerivedReturnsStateUnchangedWhenNothingWasFound()
    {
        var vector = LoadVectors().First(v => v.Producer is null);

        var enriched = Derived.WithDerived(vector.State);

        Assert.False(enriched.TryGetProperty("derived_facts", out _));
    }

    [Fact]
    public void StateWithoutEvidenceYieldsNoFacts()
    {
        var state = JsonDocument.Parse("""{"stack_trace": "boom"}""").RootElement;

        Assert.Empty(Derived.Derive(state));
    }
}
