using System.Text.Json;
using System.Text.Json.Serialization;
using ObserveAi;

namespace ObserveAi.Tests;

/// <summary>
/// Guards Tree.Combine() against drifting from eval/tree.py's combine(). The
/// vectors in tests/vectors/combine.json were generated by running the Python
/// implementation directly (see the case names for what each one covers), not
/// hand-written, so this test is only meaningful as long as that file stays a
/// faithful capture of the Python output.
/// </summary>
public class CombineTests
{
    private const double Tolerance = 1e-9;

    public sealed class CombineVector
    {
        [JsonPropertyName("name")]
        public string Name { get; init; } = "";

        [JsonPropertyName("answers")]
        public Dictionary<string, Dictionary<string, double>> Answers { get; init; } = [];

        [JsonPropertyName("evidence_present")]
        public bool EvidencePresent { get; init; }

        [JsonPropertyName("expected_bug")]
        public double ExpectedBug { get; init; }

        [JsonPropertyName("expected_downstream")]
        public double ExpectedDownstream { get; init; }

        [JsonPropertyName("expected_fallback")]
        public bool ExpectedFallback { get; init; }

        public override string ToString() => Name;
    }

    public static IEnumerable<object[]> Vectors() =>
        LoadVectors().Select(vector => new object[] { vector });

    private static List<CombineVector> LoadVectors()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "vectors", "combine.json");
        var json = File.ReadAllText(path);
        return JsonSerializer.Deserialize<List<CombineVector>>(json) ?? [];
    }

    [Theory]
    [MemberData(nameof(Vectors))]
    public void AgreesWithPythonCombine(CombineVector vector)
    {
        var tree = QuestionTree.LoadEmbedded();
        var answers = vector.Answers.ToDictionary(
            pair => pair.Key, pair => (IReadOnlyDictionary<string, double>)pair.Value);

        var result = tree.Combine(answers, vector.EvidencePresent);

        Assert.True(
            Math.Abs(vector.ExpectedBug - result.Bug) < Tolerance,
            $"{vector.Name}: expected bug {vector.ExpectedBug}, got {result.Bug}");
        Assert.True(
            Math.Abs(vector.ExpectedDownstream - result.Downstream) < Tolerance,
            $"{vector.Name}: expected downstream {vector.ExpectedDownstream}, got {result.Downstream}");
        Assert.Equal(vector.ExpectedFallback, result.Fallback);
    }

    [Fact]
    public void VectorFileIsNotEmpty()
    {
        Assert.NotEmpty(LoadVectors());
    }
}
